import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import LayoutProvider from "./layoutProvider";
import { SessionProvider } from "next-auth/react";
import NavBar from "@/components/navBar";
import { ThemeProvider } from "@/components/theme-provider";
import SideBar from "@/components/sideBar";
import { cookies } from "next/headers";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookie = cookies();
  const action = cookie.get("token")?.value !== undefined ? true : false;
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LayoutProvider>
            <NavBar />
            {children}
          </LayoutProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
